BanMiCay/BanMiCay/Controllers/DanhmucsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BanMiCay.Data;
using BanMiCay.Models;
using Microsoft.AspNetCore.Http;

namespace BanMiCay.Controllers
{
    public class DanhMucsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public DanhMucsController(ApplicationDbContext context)
        {
            _context = context;
        }

        public void GetInfo()
        {
            string email = HttpContext.Session.GetString("nhanvien");
            ViewBag.nhanvien = _context.NhanVien.FirstOrDefault(n => n.Email == email);
        }

        // GET: DanhMucs
        public async Task<IActionResult> Index()
        {
            GetInfo();
            return View(await _context.DanhMuc.ToListAsync());
        }

        // GET: DanhMucs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var danhMuc = await _context.DanhMuc
                .FirstOrDefaultAsync(m => m.Madm == id);
            if (danhMuc == null)
            {
                return NotFound();
            }
            GetInfo();
            return View(danhMuc);
        }

        // GET: DanhMucs/Create
        public IActionResult Create()
        {
            GetInfo();
            return View();
        }

        // POST: DanhMucs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Madm,Ten")] DanhMuc danhMuc)
        {
            if (ModelState.IsValid)
            {
                _context.Add(danhMuc);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            GetInfo();
            return View(danhMuc);
        }

        // GET: DanhMucs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var danhMuc = await _context.DanhMuc.FindAsync(id);
            if (danhMuc == null)
            {
                return NotFound();
            }
            GetInfo();
            return View(danhMuc);
        }

        // POST: DanhMucs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Madm,Ten")] DanhMuc danhMuc)
        {
            if (id != danhMuc.Madm)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(danhMuc);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DanhMucExists(danhMuc.Madm))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            GetInfo();
            return View(danhMuc);
        }

        // GET: DanhMucs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var danhMuc = await _context.DanhMuc
                .FirstOrDefaultAsync(m => m.Madm == id);
            if (danhMuc == null)
            {
                return NotFound();
            }
            GetInfo();
            return View(danhMuc);
        }

        // POST: DanhMucs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var danhMuc = await _context.DanhMuc.FindAsync(id);
            _context.DanhMuc.Remove(danhMuc);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DanhMucExists(int id)
        {
            return _context.DanhMuc.Any(e => e.Madm == id);
        }
    }
}

BanMiCay/BanMiCay/Controllers/MainController.cs
using BanMiCay.Data;
using BanMiCay.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BanMiCay.Controllers
{
    public class MainController : Controller
    {
        private readonly ApplicationDbContext _context;

        public MainController(ApplicationDbContext context)
        {
            _context = context;
        }
        public void GetInfo()
        {
            string email = HttpContext.Session.GetString("nhanvien");
            ViewBag.nhanvien = _context.NhanVien.FirstOrDefault(n => n.Email == email);
            ViewBag.mathang = _context.MatHang.ToList();
        }

        public IActionResult Index()
        {
            TongQuan();   
            GetInfo();
            return View();
        }
        public void TongQuan()
        {
            ViewBag.TotalOrder = _context.HoaDon.Count(x => x.Trangthai == 1);
            var lstHoaDon = _context.HoaDon.Where(d => d.Trangthai == 1);
            int tongtien = 0;
            foreach (HoaDon hd in lstHoaDon)
            {
                tongtien += hd.Tongtien;
            }
            ViewData["tongtien"] = tongtien.ToString("n0");
            ViewBag.TotalClient = _context.KhachHang.Count(k => k.Matkhau != null);
            ViewBag.TotalProduct = _context.MatHang.Count(h => h.Daxoa == 0);
        }


        // Thống kê theo ngày
        public IActionResult ThongKeTheoNgay()
        {
            GetInfo();
            return View();
        }

        [HttpPost]
        public IActionResult XemThongKeTheoNgay(DateTime Ngaybatdau, DateTime Ngayketthuc)
        {
            var lstHD = _context.HoaDon.Include(m => m.MakhNavigation).Where(d => d.Ngay >= Ngaybatdau && d.Ngay <= Ngayketthuc && d.Trangthai == 1);
            int tongtien = 0;
            foreach (HoaDon hd in lstHD)
            {
                tongtien += hd.Tongtien;
            }
            ViewData["ngaybatdau"] = Ngaybatdau.Month.ToString() + "/" + Ngaybatdau.Day.ToString() + "/" + Ngaybatdau.Year.ToString();
            ViewData["ngayketthuc"] = Ngayketthuc.Month.ToString() + "/" + Ngayketthuc.Day.ToString() + "/" + Ngayketthuc.Year.ToString();
            ViewData["tongtien"] = tongtien.ToString("n0");
            GetInfo();
            return View(lstHD);
        }

        public IActionResult ThongKeKhachHang()
        {
            GetInfo();
            return View();
        }

        public IActionResult XemThongKeKhachHang(string emailkhachhang)
        {
            var lstHoaDon = _context.HoaDon.Include(m => m.MakhNavigation)
                            .Where(h => h.MakhNavigation.Email == emailkhachhang && h.MakhNavigation.Matkhau != null && h.Trangthai == 1);
            int tongtien = 0;
            foreach (HoaDon hd in lstHoaDon)
            {
                tongtien += hd.Tongtien;
            }
            ViewBag.ttkhachhang = _context.KhachHang.FirstOrDefault(k => k.Email == emailkhachhang && k.Matkhau != null);
            ViewData["tongtien"] = tongtien.ToString("n0");
            GetInfo();
            return View(lstHoaDon);
        }



        // Thống kê theo mặt hàng
        public IActionResult ThongKeTheoMatHang()
        {
            GetInfo();
            return View();
        }

        [HttpPost]
        public IActionResult XemThongKeTheoMatHang(int id)
        {
            var lstctHD = _context.CthoaDon.Include(m => m.MamhNavigation).Where(j => j.Mamh == id);
            int tongtien = 0;
            foreach (CthoaDon cthd in lstctHD)
            {
                tongtien += cthd.Thanhtien;
            }
            ViewData["tongtien"] = tongtien.ToString("n0");
            GetInfo();
            return View(lstctHD);
        }

        
        public async Task<IActionResult> Details(int id)
        {
            var hd = _context.CthoaDon.Include(k => k.MamhNavigation).Where(m => m.Mahd == id);
            GetInfo();
            return View(await hd.ToListAsync());
        }

        public IActionResult HoaDonChuaDuyet()
        {
            var lstHoaDon = _context.HoaDon
                            .Include(k => k.MakhNavigation)
                            .Include(d => d.MadcNavigation)
                            .Where(h => h.Trangthai == 0);

            GetInfo();
            return View(lstHoaDon);
        }

        public IActionResult HoaDonDaDuyet()
        {
            var lstHoaDon = _context.HoaDon
                            .Include(k => k.MakhNavigation)
                            .Include(d => d.MadcNavigation)
                            .Where(h => h.Trangthai == 1);

            GetInfo();
            return View(lstHoaDon);
        }

        public IActionResult HoaDonDaHuy()
        {
            var lstHoaDon = _context.HoaDon
                            .Include(k => k.MakhNavigation)
                            .Include(d => d.MadcNavigation)
                            .Where(h => h.Trangthai == 2);

            GetInfo();
            return View(lstHoaDon);
        }



        public IActionResult ChiTietHoaDonChuaDuyet(int id)
        {
            HoaDon hd = _context.HoaDon
                        .Include(k => k.MakhNavigation)
                        .Include(d => d.MadcNavigation)
                        .FirstOrDefault(h => h.Mahd == id);
            var lstCTHoaDon = _context.CthoaDon.Include(c => c.MamhNavigation).Where(h => h.Mahd == id);
            ViewBag.chittiethoadon = lstCTHoaDon;
            GetInfo();
            return View(hd);
        }

        public IActionResult ChiTietHoaDonDaDuyet(int id)
        {
            HoaDon hd = _context.HoaDon
                        .Include(k => k.MakhNavigation)
                        .Include(d => d.MadcNavigation)
                        .FirstOrDefault(h => h.Mahd == id);
            var lstCTHoaDon = _context.CthoaDon.Include(c => c.MamhNavigation).Where(h => h.Mahd == id);
            ViewBag.chittiethoadon = lstCTHoaDon;
            GetInfo();
            return View(hd);
        }

        public IActionResult ChiTietHoaDonDaHuy(int id)
        {
            HoaDon hd = _context.HoaDon
                        .Include(k => k.MakhNavigation)
                        .Include(d => d.MadcNavigation)
                        .FirstOrDefault(h => h.Mahd == id);
            var lstCTHoaDon = _context.CthoaDon.Include(c => c.MamhNavigation).Where(h => h.Mahd == id);
            ViewBag.chittiethoadon = lstCTHoaDon;
            GetInfo();
            return View(hd);
        }

        public async Task<IActionResult> DuyetDonHang(int id)
        {
            HoaDon hd = _context.HoaDon.FirstOrDefault(h => h.Mahd == id);
            hd.Trangthai = 1;
            _context.Update(hd);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(HoaDonChuaDuyet));
        }

        public async Task<IActionResult> HuyDonHang(int id)
        {
            HoaDon hd = _context.HoaDon.FirstOrDefault(h => h.Mahd == id);
            hd.Trangthai = 2;
            _context.Update(hd);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(HoaDonChuaDuyet));
        }

    }
}

BanMiCay/BanMiCay/Controllers/NhanViensController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BanMiCay.Data;
using BanMiCay.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;

namespace BanMiCay.Controllers
{
    public class NhanViensController : Controller
    {
        private readonly ApplicationDbContext _context;

        private readonly IPasswordHasher<NhanVien> _nvpasswordHasher;

        public NhanViensController(ApplicationDbContext context, IPasswordHasher<NhanVien> nvpasswordHasher)
        {
            _context = context;
            _nvpasswordHasher = nvpasswordHasher;
        }

        public void GetInfo()
        {
            string email = HttpContext.Session.GetString("nhanvien");
            ViewBag.nhanvien = _context.NhanVien.FirstOrDefault(n => n.Email == email);
        }

        // GET: NhanViens
        public async Task<IActionResult> Index()
        {
            GetInfo();
            return View(await _context.NhanVien.ToListAsync());
        }

        // GET: NhanViens/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var nhanVien = await _context.NhanVien
                .FirstOrDefaultAsync(m => m.Manv == id);
            if (nhanVien == null)
            {
                return NotFound();
            }
            GetInfo();
            return View(nhanVien);
        }

        // GET: NhanViens/Create
        public IActionResult Create()
        {
            GetInfo();
            return View();
        }

        // POST: NhanViens/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Manv,Ten,Dienthoai,Email,Matkhau,Quyen")] NhanVien nhanVien, int quyen)
        {
            if (ModelState.IsValid)
            {
                if (quyen == 1)
                {
                    nhanVien.Quyen = 1;
                }
                else
                {
                    nhanVien.Quyen = 0;
                }
                nhanVien.Matkhau = _nvpasswordHasher.HashPassword(nhanVien, nhanVien.Matkhau);
                _context.Add(nhanVien);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            GetInfo();
            return View(nhanVien);
        }

        // GET: NhanViens/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var nhanVien = await _context.NhanVien.FindAsync(id);
            if (nhanVien == null)
            {
                return NotFound();
            }
            GetInfo();
            return View(nhanVien);
        }

        // POST: NhanViens/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int manv, string hoten, string email, string matkhau, int quyen)
        {
            NhanVien nv = _context.NhanVien.FirstOrDefault(n => n.Manv == manv);
            if(nv != null)
            {
                if (matkhau != null)
                {
                    nv.Matkhau = _nvpasswordHasher.HashPassword(nv, matkhau);
                }nv.Ten = hoten;

                nv.Email = email;
                nv.Quyen = quyen;
                _context.Update(nv);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));

            }
            return RedirectToAction(nameof(Edit));
        }

        // GET: NhanViens/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var nhanVien = await _context.NhanVien
                .FirstOrDefaultAsync(m => m.Manv == id);
            if (nhanVien == null)
            {
                return NotFound();
            }
            GetInfo();
            return View(nhanVien);
        }

        // POST: NhanViens/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var nhanVien = await _context.NhanVien.FindAsync(id);
            _context.NhanVien.Remove(nhanVien);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool NhanVienExists(int id)
        {
            return _context.NhanVien.Any(e => e.Manv == id);
        }
    }
}

BanMiCay/BanMiCay/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Responsive Admin &amp; Dashboard Template based on Bootstrap 5">
    <meta name="author" content="AdminKit">
    <meta name="keywords" content="adminkit, bootstrap, bootstrap 5, admin, dashboard, template, responsive, css, sass, html, theme, front-end, ui kit, web">

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="shortcut icon" href="~/Admin/img/icons/icon-48x48.png" />
    <link rel="canonical" href="https://demo-basic.adminkit.io/" />
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">      
    <link rel="stylesheet" href="~/Admin/css/adminlte.min.css">   
    <title>AdminKit Demo - Bootstrap 5 Admin Template</title>
    <link href="~/Admin/css/app.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css">
</head>

<body>
    <div class="wrapper">
        <nav id="sidebar" class="sidebar js-sidebar">
            <div class="sidebar-content js-simplebar">
                <a class="sidebar-brand" href="index.html">
                    <span class="align-middle">Admin Page</span>
                </a>

                <ul class="sidebar-nav mx-3">
                    @if (ViewBag.nhanvien.Quyen == 1)
                    {
                        <li class="sidebar-header">
                            Trang quản lý
                        </li>

                        <li class="sidebar-item active">
                            <a class="sidebar-link" asp-action="Index" asp-controller="Main">
                                <i class="align-middle" data-feather="sliders"></i> <span class="align-middle">Tổng quan</span>
                            </a>
                        </li>

                        <li class="sidebar-item">
                            <a class="sidebar-link" asp-action="Index" asp-controller="DanhMucs">
                                <i class="align-middle" data-feather="sliders"></i> <span class="align-middle">Quản lý danh mục</span>
                            </a>
                        </li>

                        <li class="sidebar-item">
                            <a class="sidebar-link" asp-action="Index" asp-controller="MatHangs">
                                <i class="align-middle" data-feather="user"></i> <span class="align-middle">Quản lý sản phẩm</span>
                            </a>
                        </li>

                        <li class="sidebar-item">
                            <a class="sidebar-link" asp-action="Index" asp-controller="KhachHangs">
                                <i class="align-middle" data-feather="log-in"></i> <span class="align-middle">Quản lý khách hàng</span>
                            </a>
                        </li>

                        <li class="sidebar-item">
                            <a class="sidebar-link" asp-action="Index" asp-controller="NhanViens">
                                <i class="align-middle" data-feather="user-plus"></i> <span class="align-middle">Quản lý nhân viên</span>
                            </a>
                        </li>

                        <li class="sidebar-header">
                            Thống kê doanh thu
                        </li>

                        <li class="sidebar-item">
                            <a class="sidebar-link" asp-action="ThongKeTheoNgay" asp-controller="Main">
                                <i class="align-middle" data-feather="square"></i> <span class="align-middle">Thống kê theo ngày</span>
                            </a>
                        </li>

                        <li class="sidebar-item">
                            <a class="sidebar-link" asp-action="ThongKeKhachHang" asp-controller="Main">
                                <i class="align-middle" data-feather="check-square"></i> <span class="align-middle">Thống kê theo khách hàng</span>
                            </a>
                        </li>

                        <li class="sidebar-item">
                            <a class="sidebar-link" asp-action="ThongKeTheoMatHang" asp-controller="Main">
                                <i class="align-middle" data-feather="check-square"></i> <span class="align-middle">Thống kê theo mặt hàng</span>
                            </a>
                        </li>
                    }


                    <li class="sidebar-header">
                        Quản lý hóa đơn
                    </li>

                    <li class="sidebar-item">
                        <a class="sidebar-link" asp-controller="Main" asp-action="HoaDonChuaDuyet">
                            <i class="align-middle" data-feather="square"></i> <span class="align-middle">Hóa đơn chưa duyệt</span>
                        </a>
                    </li>

                    <li class="sidebar-item">
                        <a class="sidebar-link" asp-controller="Main" asp-action="HoaDonDaDuyet">
                            <i class="align-middle" data-feather="check-square"></i> <span class="align-middle">Hóa đơn đã duyệt</span>
                        </a>
                    </li>

                    <li class="sidebar-item">
                        <a class="sidebar-link" asp-controller="Main" asp-action="HoaDonDaHuy">
                            <i class="align-middle" data-feather="grid"></i> <span class="align-middle">Hóa đơn đã hủy</span>
                        </a>
                    </li>


                    <li class="sidebar-item">
                        <a class="sidebar-link" asp-action="Logout" asp-controller="Home">
                            <i class="align-middle" data-feather="check-square"></i> <span class="align-middle">ĐĂNG XUẤT</span>
                        </a>
                    </li>
                </ul>
            </div>
        </nav>
        <div class="container bg-white">
            @RenderBody()
        </div>
    </div>

</body>

</html>

BanMiCay/BanMiCay/Views/Shared/_Layout1.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"></script>
    <title>Umegu</title>

    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />

</head>
<body id="top">

    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-warning shadow">
        <div class="container px-4 px-lg-5">
            <a class="navbar-brand" asp-controller="Home" asp-action="Index"><i class="bi bi-shop"></i> Umegu</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Trang chủ</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-dark" href="#" role="button" data-bs-toggle="dropdown">Danh mục</a>
                        <ul class="dropdown-menu">

                            @foreach (var i in (List<DanhMuc>)ViewBag.danhmuc)
                            {
                <li><a class="dropdown-item" asp-controller="Home" asp-action="index1" asp-route-id="@i.Madm">@i.Ten</a></li>}

                        </ul>
                    </li>
                    
                </ul>
                <div class="d-flex">
                    <div class="d-flex flex-row">
                        <form asp-controller="Home" asp-action="Search">
                            <input type="search" name="SearchKey" placeholder="Tìm kiếm...." class="form-control" />
                        </form>

                    </div>
                    @if (ViewBag.khachhang != null)
                    {
        <a asp-controller="Home" asp-action="Customer" class="btn btn-outline-light mx-1"><i class="bi bi-person"></i>@ViewBag.khachhang.Ten</a> }
    else
    {
<a asp-controller="Home" asp-action="Login" class="btn btn-outline-light mx-1"><i class="bi bi-person"></i> Đăng nhập</a>}

                    <!--<span class="badge bg-danger text-white ms-1 rounded-pill"></span>-->
                    <a class="btn btn-outline-light" asp-controller="Home" asp-action="ViewCart"><i class="bi bi-cart3"></i> Giỏ hàng <span class="badge bg-danger text-white ms-1 rounded-pill">@ViewData["SoLuongGioHang"]</span></a>
                </div>
            </div>
        </div>
    </nav>
    <!-- Section-->
    <section class="py-5">
        <div class="container px-4 px-lg-5 mt-1">
            @RenderBody()
        </div>
    </section>




    <!-- Footer-->
    <footer class="py-5 bg-warning">
        <div class="text-center mb-5"><a class="text-warning" href="#top"><i class="bi bi-chevron-up" style="font-size: 3rem; font-weight: bold; color:black;"></i></a></div>

        <div class="container">
            <div class="row">
                <div class="col-6 text-light">
                    <h4>
                        <i class="bi bi-shop"></i>Cửa hàng mì cay Umegu
                    </h4>
                    <p>
                        <b><i>Địa chỉ:</i></b> 18 Ung Văn Khiêm, phường Đông Xuyên, TP Long Xuyên, An Giang<br>
                        <b><i>Điện thoại:</i></b> 0123456798<br>
                        <b><i>Email:</i></b> abc@gmail.com
                    </p>
                </div>
                <div class="col-3 text-muted">
                    <h4>DANH MỤC HÀNG</h4>
                    @foreach (var i in (List<DanhMuc>)ViewBag.danhmuc)
                    {
        <a class="list-group-item" asp-action="index1" asp-route-id="@i.Madm">@i.Ten</a>}

                </div>
                <div class="col-3 text-muted">
                    <h4>DỊCH VỤ KHÁCH HÀNG</h4>
                    <a href="#" class="list-group-item">Hướng dẫn mua hàng</a>
                    <a href="#" class="list-group-item">Câu hỏi thường gặp</a>
                    <a href="#" class="list-group-item">Liên hệ với chúng tôi</a>
                </div>
            </div>
            <hr>
            <p class="m-0 text-center text-black-50 fw-bolder">Copyright &copy; Cửa hàng mì cay Umegu</p>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>